CREATE TABLE IF NOT EXISTS sys_log_archive (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    record_code VARCHAR(32) NOT NULL COMMENT '展示编号',
    name VARCHAR(40) NOT NULL COMMENT '日志名称',
    code VARCHAR(60) NOT NULL COMMENT '日志编码',
    status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '状态',
    owner VARCHAR(30) NOT NULL COMMENT '操作人',
    description VARCHAR(255) NOT NULL COMMENT '描述',
    log_type VARCHAR(16) NOT NULL COMMENT '日志类型',
    target VARCHAR(180) NOT NULL DEFAULT '' COMMENT '目标对象',
    ip_address VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'IP 地址',
    device_info VARCHAR(255) NOT NULL DEFAULT '' COMMENT '设备信息',
    user_agent TEXT COMMENT '原始User-Agent',
    browser VARCHAR(64) NOT NULL DEFAULT '' COMMENT '浏览器名称',
    browser_version VARCHAR(64) NOT NULL DEFAULT '' COMMENT '浏览器版本',
    os_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '操作系统名称',
    os_version VARCHAR(64) NOT NULL DEFAULT '' COMMENT '操作系统版本',
    device_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '设备类型',
    device_brand VARCHAR(64) NOT NULL DEFAULT '' COMMENT '设备品牌',
    request_info TEXT COMMENT '请求信息',
    response_info TEXT COMMENT '响应信息',
    result VARCHAR(20) NOT NULL DEFAULT '' COMMENT '结果',
    duration_ms BIGINT NOT NULL DEFAULT 0 COMMENT '耗时',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记',
    created_at DATETIME NOT NULL COMMENT '原始创建时间',
    updated_at DATETIME NOT NULL COMMENT '原始更新时间',
    archived_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '归档时间',
    UNIQUE KEY uk_sys_log_archive_record_code (record_code),
    KEY idx_sys_log_archive_query (log_type, status, created_at),
    KEY idx_sys_log_archive_archived_at (archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统日志留档表';
