CREATE TABLE IF NOT EXISTS point_account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    available_points BIGINT NOT NULL DEFAULT 0 COMMENT '可用积分',
    frozen_points BIGINT NOT NULL DEFAULT 0 COMMENT '冻结积分',
    total_earned_points BIGINT NOT NULL DEFAULT 0 COMMENT '累计获得积分',
    total_spent_points BIGINT NOT NULL DEFAULT 0 COMMENT '累计消耗积分',
    version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_point_account_user_id (user_id),
    KEY idx_point_account_status (status),
    CONSTRAINT chk_point_account_available_non_negative CHECK (available_points >= 0),
    CONSTRAINT chk_point_account_frozen_non_negative CHECK (frozen_points >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分账户表';

CREATE TABLE IF NOT EXISTS point_ledger (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    ledger_no VARCHAR(64) NOT NULL COMMENT '流水号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    account_id BIGINT NOT NULL COMMENT '积分账户ID',
    direction VARCHAR(32) NOT NULL COMMENT '流水方向',
    amount BIGINT NOT NULL COMMENT '变动积分',
    balance_before BIGINT NOT NULL COMMENT '变动前可用余额',
    balance_after BIGINT NOT NULL COMMENT '变动后可用余额',
    frozen_before BIGINT NOT NULL COMMENT '变动前冻结余额',
    frozen_after BIGINT NOT NULL COMMENT '变动后冻结余额',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_no VARCHAR(64) NOT NULL COMMENT '业务单号',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    operator_type VARCHAR(32) NOT NULL COMMENT '操作人类型',
    operator_id VARCHAR(64) NOT NULL COMMENT '操作人',
    trace_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '链路ID',
    prev_hash VARCHAR(128) NOT NULL COMMENT '上一条流水哈希',
    entry_hash VARCHAR(128) NOT NULL COMMENT '当前流水哈希',
    remark VARCHAR(512) NOT NULL DEFAULT '' COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_point_ledger_no (ledger_no),
    UNIQUE KEY uk_point_ledger_biz_direction (biz_type, biz_no, direction),
    UNIQUE KEY uk_point_ledger_user_idempotency (user_id, idempotency_key),
    KEY idx_point_ledger_user_created_at (user_id, created_at),
    KEY idx_point_ledger_biz_no (biz_no),
    KEY idx_point_ledger_account_id (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分账本流水表';

CREATE TABLE IF NOT EXISTS point_recharge_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    recharge_no VARCHAR(64) NOT NULL COMMENT '充值单号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    channel VARCHAR(32) NOT NULL COMMENT '充值渠道',
    amount BIGINT NOT NULL COMMENT '充值积分',
    status VARCHAR(32) NOT NULL COMMENT '状态',
    external_no VARCHAR(128) NOT NULL DEFAULT '' COMMENT '外部流水号',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    request_snapshot JSON NULL COMMENT '请求摘要',
    result_snapshot JSON NULL COMMENT '结果摘要',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_point_recharge_no (recharge_no),
    UNIQUE KEY uk_point_recharge_channel_external (channel, external_no),
    UNIQUE KEY uk_point_recharge_user_idempotency (user_id, idempotency_key),
    KEY idx_point_recharge_user_created_at (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分充值单表';

CREATE TABLE IF NOT EXISTS point_freeze_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    freeze_no VARCHAR(64) NOT NULL COMMENT '冻结单号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    amount BIGINT NOT NULL COMMENT '冻结积分',
    biz_type VARCHAR(64) NOT NULL COMMENT '业务类型',
    biz_no VARCHAR(64) NOT NULL COMMENT '业务单号',
    status VARCHAR(32) NOT NULL COMMENT '状态',
    expire_at DATETIME NOT NULL COMMENT '过期时间',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_point_freeze_no (freeze_no),
    UNIQUE KEY uk_point_freeze_biz (biz_type, biz_no),
    UNIQUE KEY uk_point_freeze_user_idempotency (user_id, idempotency_key),
    KEY idx_point_freeze_user_created_at (user_id, created_at),
    KEY idx_point_freeze_expire_status (status, expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分冻结单表';

CREATE TABLE IF NOT EXISTS point_adjustment_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    adjust_no VARCHAR(64) NOT NULL COMMENT '调整单号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    direction VARCHAR(32) NOT NULL COMMENT '调整方向',
    amount BIGINT NOT NULL COMMENT '调整积分',
    status VARCHAR(32) NOT NULL COMMENT '状态',
    reason VARCHAR(512) NOT NULL COMMENT '申请原因',
    ticket_no VARCHAR(128) NOT NULL COMMENT '工单号或附件引用',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    applicant VARCHAR(64) NOT NULL COMMENT '申请人',
    approver VARCHAR(64) DEFAULT NULL COMMENT '审批人',
    approved_at DATETIME DEFAULT NULL COMMENT '审批时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_point_adjust_no (adjust_no),
    UNIQUE KEY uk_point_adjust_user_idempotency (user_id, idempotency_key),
    KEY idx_point_adjust_user_created_at (user_id, created_at),
    KEY idx_point_adjust_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分人工调整单表';
