CREATE TABLE IF NOT EXISTS credential_category (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    category_code VARCHAR(64) NOT NULL COMMENT '分类编码',
    category_name VARCHAR(100) NOT NULL COMMENT '分类名称',
    fulfillment_type VARCHAR(32) NOT NULL COMMENT '履约类型',
    generation_mode VARCHAR(32) NOT NULL COMMENT '生成模式',
    payload_schema JSON NULL COMMENT '履约参数结构',
    import_config JSON NULL COMMENT '导入配置',
    extract_policy JSON NULL COMMENT '提取策略',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_credential_category_code (category_code),
    KEY idx_credential_category_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证分类表';

CREATE TABLE IF NOT EXISTS credential_batch (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    batch_no VARCHAR(64) NOT NULL COMMENT '批次号',
    batch_name VARCHAR(100) NOT NULL COMMENT '批次名称',
    category_id BIGINT NOT NULL COMMENT '凭证分类ID',
    fulfillment_type VARCHAR(32) NOT NULL COMMENT '履约类型快照',
    generation_mode VARCHAR(32) NOT NULL COMMENT '生成模式',
    payload_config JSON NULL COMMENT '履约配置',
    total_count INT NOT NULL DEFAULT 0 COMMENT '总数量',
    available_count INT NOT NULL DEFAULT 0 COMMENT '可用数量',
    consumed_count INT NOT NULL DEFAULT 0 COMMENT '已兑换或已提取数量',
    linked_count INT NOT NULL DEFAULT 0 COMMENT '已绑定链接数量',
    valid_from DATETIME NOT NULL COMMENT '生效时间',
    valid_to DATETIME NOT NULL COMMENT '失效时间',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    created_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_credential_batch_no (batch_no),
    KEY idx_credential_batch_category_status (category_id, status),
    KEY idx_credential_batch_valid_time (valid_from, valid_to),
    KEY idx_credential_batch_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证批次表';

CREATE TABLE IF NOT EXISTS credential_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    batch_id BIGINT NOT NULL COMMENT '批次ID',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    item_no VARCHAR(64) NOT NULL COMMENT '明细编号',
    secret_hash VARCHAR(128) NOT NULL COMMENT '敏感文本HMAC',
    encrypted_secret TEXT NOT NULL COMMENT '加密后的敏感文本',
    secret_mask VARCHAR(128) NOT NULL DEFAULT '' COMMENT '脱敏展示值',
    checksum VARCHAR(16) NOT NULL DEFAULT '' COMMENT '校验位或短摘要',
    payload_snapshot JSON NULL COMMENT '履约配置快照',
    source_type VARCHAR(32) NOT NULL COMMENT '来源类型',
    source_line_no INT DEFAULT NULL COMMENT '导入行号',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    consumed_user_id BIGINT DEFAULT NULL COMMENT '兑换用户ID',
    consumed_at DATETIME DEFAULT NULL COMMENT '兑换或首次提取时间',
    consume_biz_no VARCHAR(64) DEFAULT NULL COMMENT '消费业务单号',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_credential_item_no (item_no),
    UNIQUE KEY uk_credential_item_secret_hash (secret_hash),
    KEY idx_credential_item_batch_status (batch_id, status),
    KEY idx_credential_item_category_status (category_id, status),
    KEY idx_credential_item_consumed_user (consumed_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证明细表';

CREATE TABLE IF NOT EXISTS credential_extract_link (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    link_no VARCHAR(64) NOT NULL COMMENT '链接编号',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    batch_id BIGINT NOT NULL COMMENT '批次ID',
    token_hash VARCHAR(128) NOT NULL COMMENT 'Token HMAC',
    encrypted_token TEXT DEFAULT NULL COMMENT '加密后的Token',
    token_key_id VARCHAR(64) DEFAULT NULL COMMENT 'Token密钥版本',
    item_count INT NOT NULL DEFAULT 0 COMMENT '包含凭证数量',
    max_access_count INT NOT NULL COMMENT '最大成功访问次数',
    accessed_count INT NOT NULL DEFAULT 0 COMMENT '已成功访问次数',
    expire_at DATETIME NOT NULL COMMENT '过期时间',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态',
    created_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    disabled_by BIGINT DEFAULT NULL COMMENT '停用人ID',
    disabled_at DATETIME DEFAULT NULL COMMENT '停用时间',
    last_accessed_at DATETIME DEFAULT NULL COMMENT '最近成功访问时间',
    remark VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_credential_extract_link_no (link_no),
    UNIQUE KEY uk_credential_extract_token_hash (token_hash),
    KEY idx_credential_extract_batch_status (batch_id, status),
    KEY idx_credential_extract_category_status (category_id, status),
    KEY idx_credential_extract_expire (expire_at),
    KEY idx_credential_extract_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证提取链接表';

CREATE TABLE IF NOT EXISTS credential_extract_link_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    link_id BIGINT NOT NULL COMMENT '提取链接ID',
    item_id BIGINT NOT NULL COMMENT '凭证明细ID',
    batch_id BIGINT NOT NULL COMMENT '批次ID',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '展示顺序',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_credential_extract_link_item (link_id, item_id),
    KEY idx_credential_extract_link_item_link (link_id, sort_no),
    KEY idx_credential_extract_link_item_item (item_id),
    KEY idx_credential_extract_link_item_batch (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证提取链接明细表';

CREATE TABLE IF NOT EXISTS credential_extract_access_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    access_no VARCHAR(64) NOT NULL COMMENT '访问流水号',
    link_id BIGINT DEFAULT NULL COMMENT '提取链接ID',
    batch_id BIGINT DEFAULT NULL COMMENT '批次ID',
    item_count INT NOT NULL DEFAULT 0 COMMENT '本次返回凭证数量',
    success TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否成功',
    failure_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT '失败原因',
    client_ip VARCHAR(64) NOT NULL DEFAULT '' COMMENT '访问IP',
    user_agent_hash VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'UA摘要',
    browser_fingerprint VARCHAR(128) NOT NULL DEFAULT '' COMMENT '浏览器指纹',
    device_snapshot JSON NULL COMMENT '设备摘要',
    trace_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_credential_extract_access_no (access_no),
    KEY idx_credential_extract_access_link_created (link_id, created_at),
    KEY idx_credential_extract_access_batch_created (batch_id, created_at),
    KEY idx_credential_extract_access_fingerprint (browser_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证提取访问记录表';

CREATE TABLE IF NOT EXISTS credential_import_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    task_no VARCHAR(64) NOT NULL COMMENT '导入任务号',
    batch_id BIGINT DEFAULT NULL COMMENT '批次ID',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    delimiter VARCHAR(32) NOT NULL COMMENT '分隔符',
    total_rows INT NOT NULL DEFAULT 0 COMMENT '解析总行数',
    valid_rows INT NOT NULL DEFAULT 0 COMMENT '有效行数',
    duplicate_rows INT NOT NULL DEFAULT 0 COMMENT '重复行数',
    invalid_rows INT NOT NULL DEFAULT 0 COMMENT '无效行数',
    import_hash VARCHAR(128) NOT NULL DEFAULT '' COMMENT '原始导入内容摘要',
    result_summary JSON NULL COMMENT '导入结果摘要',
    status VARCHAR(32) NOT NULL DEFAULT 'previewed' COMMENT '状态',
    created_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_credential_import_task_no (task_no),
    KEY idx_credential_import_batch (batch_id),
    KEY idx_credential_import_category_status (category_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证导入任务表';

CREATE TABLE IF NOT EXISTS credential_redeem_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    record_no VARCHAR(64) NOT NULL COMMENT '兑换记录号',
    item_id BIGINT DEFAULT NULL COMMENT '凭证明细ID',
    batch_id BIGINT DEFAULT NULL COMMENT '批次ID',
    category_id BIGINT DEFAULT NULL COMMENT '分类ID',
    user_id BIGINT NOT NULL COMMENT '兑换用户ID',
    points BIGINT NOT NULL DEFAULT 0 COMMENT '入账积分',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    client_ip VARCHAR(64) NOT NULL DEFAULT '' COMMENT '兑换IP',
    user_agent_hash VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'UA摘要',
    device_fingerprint VARCHAR(128) NOT NULL DEFAULT '' COMMENT '设备指纹',
    ledger_no VARCHAR(64) DEFAULT NULL COMMENT '积分账本流水号',
    status VARCHAR(32) NOT NULL COMMENT '状态',
    failure_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT '失败原因',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_credential_redeem_record_no (record_no),
    UNIQUE KEY uk_credential_redeem_user_idempotency (user_id, idempotency_key),
    KEY idx_credential_redeem_user_created (user_id, created_at),
    KEY idx_credential_redeem_batch_status (batch_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证兑换记录表';

CREATE TABLE IF NOT EXISTS credential_operation_audit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    audit_no VARCHAR(64) NOT NULL COMMENT '审计编号',
    operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
    operation_type VARCHAR(64) NOT NULL COMMENT '操作类型',
    target_type VARCHAR(32) NOT NULL COMMENT '目标类型',
    target_id BIGINT DEFAULT NULL COMMENT '目标ID',
    before_snapshot JSON NULL COMMENT '操作前脱敏快照',
    after_snapshot JSON NULL COMMENT '操作后脱敏快照',
    client_ip VARCHAR(64) NOT NULL DEFAULT '' COMMENT '管理端IP',
    success TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否成功',
    failure_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT '失败原因',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_credential_operation_audit_no (audit_no),
    KEY idx_credential_operation_target (target_type, target_id),
    KEY idx_credential_operation_operator_created (operator_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证操作审计表';

CREATE TABLE IF NOT EXISTS risk_alert (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    alert_no VARCHAR(64) NOT NULL COMMENT '告警编号',
    alert_type VARCHAR(64) NOT NULL COMMENT '告警类型',
    risk_level VARCHAR(32) NOT NULL COMMENT '风险等级',
    subject_type VARCHAR(64) NOT NULL COMMENT '对象类型',
    subject_no VARCHAR(128) NOT NULL COMMENT '对象编号',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    status VARCHAR(32) NOT NULL DEFAULT 'open' COMMENT '状态',
    detail_snapshot JSON NULL COMMENT '告警详情',
    handled_by VARCHAR(64) DEFAULT NULL COMMENT '处理人',
    handled_at DATETIME DEFAULT NULL COMMENT '处理时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_risk_alert_no (alert_no),
    KEY idx_risk_alert_status_created_at (status, created_at),
    KEY idx_risk_alert_subject (subject_type, subject_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='风险告警表';
